---
name: 手写数字图片MNIST
author: 李渊
description: 手写数字图片MNIST
topic: 手写数字图片MNIST
algorithm: CNN
language: flyai_env/bin/

framework: Tensorflow

data:
  id: MNIST
  name: 手写数字图片MNIST
  category: image

model:
  processor: Processor
  input_x: input_x
  output_x: input_x
  input_y: input_y
  output_y: output_y
  input:
    columns:
      - name: image_path
        type: url
    to_type: float
    to_shape: [-1,784]
  output:
    columns:
      - name: label
        type: int
    to_type: int
    to_shape: [-1，10]
servers:
  - id: flyai
    url: https://flyai.com
...